agent {
  data_dir = "/run/spire"
  log_level = "INFO"
  server_address = "spire-server"
  server_port = "8081"
  socket_path = "/tmp/spire-agent-api/api.sock"
  trust_bundle_path = "/run/spire/bundle.crt"
  trust_domain = "example.org"
}

plugins {
  NodeAttestor "join_token" {
    plugin_data {}
  }

  KeyManager "memory" {
    plugin_data {}
  }

  WorkloadAttestor "docker" {
    plugin_data {}
  }

  WorkloadAttestor "unix" {
    plugin_data {}
  }
}
