apiVersion: v1
kind: Service
metadata:
  name: {{ include "tessera-mesh.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tessera-mesh.labels" . | nindent 4 }}
  annotations:
    tessera.dev/version: {{ .Chart.AppVersion | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    {{- include "tessera-mesh.selectorLabels" . | nindent 4 }}
