{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tessera-mesh.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tessera-mesh.labels" . | nindent 4 }}
  annotations:
    tessera.dev/version: {{ .Chart.AppVersion | quote }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
{{- end }}
