"""Tessera: signed provenance labels and taint-tracking policy for LLM context."""

from tessera.approval import ApprovalGate, ApprovalRequest, ApprovalResponse, AsyncApprovalGate
from tessera.a2a import (
    A2APromptSegment,
    A2ASecurityContext,
    A2ATaskRequest,
    A2AVerificationError,
    attach_security_context,
    extract_security_context,
)
from tessera.context import Context, LabeledSegment, make_segment
from tessera.control_plane import (
    AgentHeartbeat,
    ControlPlaneState,
    ControlPlaneSigningNotAvailable,
    HMACControlPlaneSigner,
    HMACControlPlaneVerifier,
    JWTControlPlaneSigner,
    JWTControlPlaneVerifier,
    OPAControlConfig,
    PolicyDistributionInput,
    RegistryDistributionInput,
    SignedControlPlaneDocument,
    create_control_plane_app,
)
from tessera.delegation import (
    DelegationNarrowingViolation,
    DelegationToken,
    narrow_delegation,
    sign_delegation,
    verify_delegation,
)
from tessera.liveness import LivenessChecker, LivenessState
from tessera.hooks.compatibility import (
    HookEvent,
    IncompatibleDecisionError,
    valid_decisions,
    validate_decision,
)
from tessera.evidence import (
    EvidenceBundle,
    EvidenceSigningNotAvailable,
    HMACEvidenceSigner,
    HMACEvidenceVerifier,
    JWTEvidenceSigner,
    JWTEvidenceVerifier,
    SignedEvidenceBundle,
)
from tessera.events import (
    AsyncWebhookSink,
    EvidenceBuffer,
    EventKind,
    EventSink,
    SecurityEvent,
    async_webhook_sink,
    emit as emit_event,
    register_sink,
    stdout_sink,
    unregister_sink,
    webhook_sink,
)
from tessera.ir import (
    CELRuleIR,
    PolicyIR,
    ResourceRequirementIR,
    compile_policy,
)
from tessera.identity import (
    AgentIdentity,
    AgentIdentityVerifier,
    AgentProofReplayCache,
    AgentProofSigner,
    AgentProofVerifier,
    JWKSAgentIdentityVerifier,
    JWTAgentIdentitySigner,
    JWTAgentIdentityVerifier,
    jwk_thumbprint,
)
from tessera.labels import Origin, TrustLabel, TrustLevel, sign_label, verify_label
from tessera.cel_engine import CELContext, CELDecision, CELNotAvailable, CELPolicyEngine, CELRule
from tessera.mcp import MCPInterceptor, MCPSecurityContext
from tessera.mtls import MTLSPeerIdentity, MTLSPeerVerificationError, extract_peer_identity
from tessera.policy import (
    Decision,
    DecisionKind,
    Policy,
    PolicyScope,
    PolicyViolation,
    ResourceRequirement,
    ResourceType,
    ToolRequirement,
)
from tessera.policy_backends import (
    OPAPolicyBackend,
    OPAStatus,
    PolicyBackend,
    PolicyBackendDecision,
    PolicyBackendError,
    PolicyDelegationSummary,
    PolicyInput,
    PolicySegmentSummary,
)
from tessera.provenance import (
    ContextSegmentEnvelope,
    ManifestSegmentRef,
    PromptProvenanceManifest,
)
from tessera.quarantine import (
    QuarantinedExecutor,
    WorkerReport,
    WorkerSchemaViolation,
    split_by_trust,
    strict_worker,
)
from tessera.replay import (
    Agreement,
    Label,
    LabelStore,
    PolicyDecision as CandidatePolicyDecision,
    ReplayCase,
    ReplayResult,
    ReplayStats,
    iter_replay_cases,
    replay,
    run_replay,
    score as score_replay,
)
from tessera.compliance import ChainedAuditLog, enrich_event
from tessera.risk.cooldown import CooldownEscalator
from tessera.risk.forecaster import SessionRisk, SessionRiskForecaster
from tessera.risk.irreversibility import IrreversibilityScore, score_irreversibility
from tessera.hooks.client import RemoteHookClient
from tessera.hooks.dispatcher import (
    HookDispatcher,
    PostPolicyEvaluateHook,
    PostToolCallGateHook,
)
from tessera.redaction import Secret, SecretRegistry, redact_nested
from tessera.registry import ToolRegistry
from tessera.ratelimit import BudgetStatus, TokenBudget
from tessera.scanners.canary import CanaryGuard
from tessera.scanners.heuristic import injection_score
from tessera.scanners.pii import PIIEntity, PIIScanner
from tessera.xds.client import XDSClient
from tessera.xds.server import XDSServer
from tessera.adapters.langchain import LangChainNotAvailable, TesseraCallbackHandler
from tessera.adapters.mcp_proxy import MCPNotAvailable, MCPTrustProxy
from tessera.adapters.openai_agents import OpenAIAgentsNotAvailable, TesseraAgentHooks
from tessera.adapters.upstream import PROVIDERS, anthropic_upstream, openai_upstream
from tessera.sessions import PendingApproval, SessionStore
from tessera.signing import (
    HMACSigner,
    HMACVerifier,
    JWKSVerifier,
    JWTSigner,
    JWTVerifier,
    LabelSigner,
    LabelVerifier,
    SigningNotAvailable,
)
from tessera.ssrf_guard import SSRFCheckResult, SSRFFinding, SSRFGuard
from tessera.spire import (
    SpireJWKSFetcher,
    SpireJWTSource,
    SpireNotAvailable,
    SpireProtocolError,
    create_spire_identity_verifier,
)

__all__ = [
    "A2APromptSegment",
    "ApprovalGate",
    "ApprovalRequest",
    "ApprovalResponse",
    "AsyncApprovalGate",
    "A2ASecurityContext",
    "A2ATaskRequest",
    "A2AVerificationError",
    "CELContext",
    "CELDecision",
    "CELNotAvailable",
    "CELPolicyEngine",
    "CELRule",
    "CELRuleIR",
    "CanaryGuard",
    "ChainedAuditLog",
    "CooldownEscalator",
    "AgentIdentity",
    "AgentIdentityVerifier",
    "AgentHeartbeat",
    "AgentProofReplayCache",
    "AgentProofSigner",
    "AgentProofVerifier",
    "AsyncWebhookSink",
    "Context",
    "ControlPlaneState",
    "ControlPlaneSigningNotAvailable",
    "ContextSegmentEnvelope",
    "Decision",
    "DecisionKind",
    "DelegationNarrowingViolation",
    "DelegationToken",
    "HookEvent",
    "IncompatibleDecisionError",
    "LivenessChecker",
    "LivenessState",
    "narrow_delegation",
    "valid_decisions",
    "validate_decision",
    "EvidenceBundle",
    "EvidenceBuffer",
    "EvidenceSigningNotAvailable",
    "EventKind",
    "EventSink",
    "HMACSigner",
    "HMACEvidenceSigner",
    "HMACEvidenceVerifier",
    "HMACControlPlaneSigner",
    "HMACControlPlaneVerifier",
    "HMACVerifier",
    "HookDispatcher",
    "BudgetStatus",
    "IrreversibilityScore",
    "PIIEntity",
    "PIIScanner",
    "TokenBudget",
    "SessionRisk",
    "SessionRiskForecaster",
    "enrich_event",
    "injection_score",
    "score_irreversibility",
    "PostPolicyEvaluateHook",
    "PostToolCallGateHook",
    "JWKSAgentIdentityVerifier",
    "JWKSVerifier",
    "JWTControlPlaneSigner",
    "JWTControlPlaneVerifier",
    "JWTAgentIdentitySigner",
    "JWTEvidenceSigner",
    "JWTEvidenceVerifier",
    "JWTSigner",
    "JWTAgentIdentityVerifier",
    "JWTVerifier",
    "LabelSigner",
    "LabelVerifier",
    "LabeledSegment",
    "ManifestSegmentRef",
    "MCPInterceptor",
    "MCPSecurityContext",
    "MTLSPeerIdentity",
    "MTLSPeerVerificationError",
    "OPAStatus",
    "OPAControlConfig",
    "Origin",
    "OPAPolicyBackend",
    "PolicyIR",
    "Policy",
    "PolicyBackend",
    "PolicyBackendDecision",
    "PolicyBackendError",
    "PolicyDistributionInput",
    "PolicyDelegationSummary",
    "PolicyInput",
    "PolicyScope",
    "PolicyViolation",
    "PolicySegmentSummary",
    "PromptProvenanceManifest",
    "QuarantinedExecutor",
    "Agreement",
    "CandidatePolicyDecision",
    "Label",
    "LabelStore",
    "ReplayCase",
    "ReplayResult",
    "ReplayStats",
    "iter_replay_cases",
    "replay",
    "run_replay",
    "score_replay",
    "Secret",
    "SecretRegistry",
    "SecurityEvent",
    "SigningNotAvailable",
    "SignedControlPlaneDocument",
    "SpireJWKSFetcher",
    "SpireJWTSource",
    "SpireNotAvailable",
    "SpireProtocolError",
    "SSRFCheckResult",
    "SSRFFinding",
    "SSRFGuard",
    "SignedEvidenceBundle",
    "ResourceRequirement",
    "ResourceRequirementIR",
    "ResourceType",
    "RemoteHookClient",
    "RegistryDistributionInput",
    "PendingApproval",
    "SessionStore",
    "ToolRegistry",
    "ToolRequirement",
    "TrustLabel",
    "TrustLevel",
    "WorkerReport",
    "WorkerSchemaViolation",
    "XDSClient",
    "XDSServer",
    "LangChainNotAvailable",
    "MCPNotAvailable",
    "MCPTrustProxy",
    "OpenAIAgentsNotAvailable",
    "TesseraAgentHooks",
    "TesseraCallbackHandler",
    "PROVIDERS",
    "anthropic_upstream",
    "openai_upstream",
    "attach_security_context",
    "compile_policy",
    "async_webhook_sink",
    "create_control_plane_app",
    "emit_event",
    "extract_security_context",
    "extract_peer_identity",
    "make_segment",
    "redact_nested",
    "register_sink",
    "sign_label",
    "sign_delegation",
    "split_by_trust",
    "stdout_sink",
    "strict_worker",
    "create_spire_identity_verifier",
    "unregister_sink",
    "verify_delegation",
    "verify_label",
    "webhook_sink",
    "jwk_thumbprint",
]
