"""Tessera: signed provenance labels and taint-tracking policy for LLM context."""

from tessera.a2a import (
    A2APromptSegment,
    A2ASecurityContext,
    A2ATaskRequest,
    A2AVerificationError,
    attach_security_context,
    extract_security_context,
)
from tessera.context import Context, LabeledSegment, make_segment
from tessera.control_plane import (
    AgentHeartbeat,
    ControlPlaneState,
    OPAControlConfig,
    PolicyDistributionInput,
    RegistryDistributionInput,
    create_control_plane_app,
)
from tessera.delegation import DelegationToken, sign_delegation, verify_delegation
from tessera.evidence import (
    EvidenceBundle,
    EvidenceSigningNotAvailable,
    HMACEvidenceSigner,
    HMACEvidenceVerifier,
    JWTEvidenceSigner,
    JWTEvidenceVerifier,
    SignedEvidenceBundle,
)
from tessera.events import (
    AsyncWebhookSink,
    EvidenceBuffer,
    EventKind,
    EventSink,
    SecurityEvent,
    async_webhook_sink,
    emit as emit_event,
    register_sink,
    stdout_sink,
    unregister_sink,
    webhook_sink,
)
from tessera.identity import (
    AgentIdentity,
    AgentIdentityVerifier,
    AgentProofReplayCache,
    AgentProofSigner,
    AgentProofVerifier,
    JWKSAgentIdentityVerifier,
    JWTAgentIdentitySigner,
    JWTAgentIdentityVerifier,
    jwk_thumbprint,
)
from tessera.labels import Origin, TrustLabel, TrustLevel, sign_label, verify_label
from tessera.mcp import MCPInterceptor, MCPSecurityContext
from tessera.mtls import MTLSPeerIdentity, MTLSPeerVerificationError, extract_peer_identity
from tessera.policy import Decision, Policy, PolicyViolation, ToolRequirement
from tessera.policy_backends import (
    OPAPolicyBackend,
    OPAStatus,
    PolicyBackend,
    PolicyBackendDecision,
    PolicyBackendError,
    PolicyDelegationSummary,
    PolicyInput,
    PolicySegmentSummary,
)
from tessera.provenance import (
    ContextSegmentEnvelope,
    ManifestSegmentRef,
    PromptProvenanceManifest,
)
from tessera.quarantine import (
    QuarantinedExecutor,
    WorkerReport,
    WorkerSchemaViolation,
    split_by_trust,
    strict_worker,
)
from tessera.redaction import Secret, SecretRegistry, redact_nested
from tessera.registry import ToolRegistry
from tessera.signing import (
    HMACSigner,
    HMACVerifier,
    JWKSVerifier,
    JWTSigner,
    JWTVerifier,
    LabelSigner,
    LabelVerifier,
    SigningNotAvailable,
)
from tessera.spire import (
    SpireJWKSFetcher,
    SpireJWTSource,
    SpireNotAvailable,
    SpireProtocolError,
    create_spire_identity_verifier,
)

__all__ = [
    "A2APromptSegment",
    "A2ASecurityContext",
    "A2ATaskRequest",
    "A2AVerificationError",
    "AgentIdentity",
    "AgentIdentityVerifier",
    "AgentHeartbeat",
    "AgentProofReplayCache",
    "AgentProofSigner",
    "AgentProofVerifier",
    "AsyncWebhookSink",
    "Context",
    "ControlPlaneState",
    "ContextSegmentEnvelope",
    "Decision",
    "DelegationToken",
    "EvidenceBundle",
    "EvidenceBuffer",
    "EvidenceSigningNotAvailable",
    "EventKind",
    "EventSink",
    "HMACSigner",
    "HMACEvidenceSigner",
    "HMACEvidenceVerifier",
    "HMACVerifier",
    "JWKSAgentIdentityVerifier",
    "JWKSVerifier",
    "JWTAgentIdentitySigner",
    "JWTEvidenceSigner",
    "JWTEvidenceVerifier",
    "JWTSigner",
    "JWTAgentIdentityVerifier",
    "JWTVerifier",
    "LabelSigner",
    "LabelVerifier",
    "LabeledSegment",
    "ManifestSegmentRef",
    "MCPInterceptor",
    "MCPSecurityContext",
    "MTLSPeerIdentity",
    "MTLSPeerVerificationError",
    "OPAStatus",
    "OPAControlConfig",
    "Origin",
    "OPAPolicyBackend",
    "Policy",
    "PolicyBackend",
    "PolicyBackendDecision",
    "PolicyBackendError",
    "PolicyDistributionInput",
    "PolicyDelegationSummary",
    "PolicyInput",
    "PolicyViolation",
    "PolicySegmentSummary",
    "PromptProvenanceManifest",
    "QuarantinedExecutor",
    "Secret",
    "SecretRegistry",
    "SecurityEvent",
    "SigningNotAvailable",
    "SpireJWKSFetcher",
    "SpireJWTSource",
    "SpireNotAvailable",
    "SpireProtocolError",
    "SignedEvidenceBundle",
    "RegistryDistributionInput",
    "ToolRegistry",
    "ToolRequirement",
    "TrustLabel",
    "TrustLevel",
    "WorkerReport",
    "WorkerSchemaViolation",
    "attach_security_context",
    "async_webhook_sink",
    "create_control_plane_app",
    "emit_event",
    "extract_security_context",
    "extract_peer_identity",
    "make_segment",
    "redact_nested",
    "register_sink",
    "sign_label",
    "sign_delegation",
    "split_by_trust",
    "stdout_sink",
    "strict_worker",
    "create_spire_identity_verifier",
    "unregister_sink",
    "verify_delegation",
    "verify_label",
    "webhook_sink",
    "jwk_thumbprint",
]
