# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tessera/xds/v1/discovery.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tessera/xds/v1/discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etessera/xds/v1/discovery.proto\x12\x14tessera_proto.xds.v1\"h\n\x10\x44iscoveryRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x14\n\x0cversion_info\x18\x03 \x01(\t\x12\x16\n\x0eresource_names\x18\x04 \x03(\t\"\x84\x01\n\x11\x44iscoveryResponse\x12\x14\n\x0cversion_info\x18\x01 \x01(\t\x12\x10\n\x08type_url\x18\x02 \x01(\t\x12\x38\n\tresources\x18\x03 \x03(\x0b\x32%.tessera_proto.xds.v1.ResourceWrapper\x12\r\n\x05nonce\x18\x04 \x01(\t\"B\n\x0fResourceWrapper\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x10\n\x08resource\x18\x03 \x01(\x0c\x32\xe7\x01\n\x1a\x41ggregatedDiscoveryService\x12\x66\n\x0fStreamResources\x12&.tessera_proto.xds.v1.DiscoveryRequest\x1a\'.tessera_proto.xds.v1.DiscoveryResponse(\x01\x30\x01\x12\x61\n\x0e\x46\x65tchResources\x12&.tessera_proto.xds.v1.DiscoveryRequest\x1a\'.tessera_proto.xds.v1.DiscoveryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tessera.xds.v1.discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISCOVERYREQUEST']._serialized_start=56
  _globals['_DISCOVERYREQUEST']._serialized_end=160
  _globals['_DISCOVERYRESPONSE']._serialized_start=163
  _globals['_DISCOVERYRESPONSE']._serialized_end=295
  _globals['_RESOURCEWRAPPER']._serialized_start=297
  _globals['_RESOURCEWRAPPER']._serialized_end=363
  _globals['_AGGREGATEDDISCOVERYSERVICE']._serialized_start=366
  _globals['_AGGREGATEDDISCOVERYSERVICE']._serialized_end=597
# @@protoc_insertion_point(module_scope)
