# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tessera/xds/v1/resources.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tessera/xds/v1/resources.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etessera/xds/v1/resources.proto\x12\x14tessera_proto.xds.v1\"\xa9\x01\n\x0cPolicyBundle\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x10\n\x08revision\x18\x02 \x01(\t\x12;\n\x0crequirements\x18\x03 \x03(\x0b\x32%.tessera_proto.xds.v1.ToolRequirement\x12\x1b\n\x13\x64\x65\x66\x61ult_trust_level\x18\x04 \x01(\x05\x12\x1c\n\x14human_approval_tools\x18\x05 \x03(\t\"N\n\x0fToolRequirement\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x16\n\x0erequired_trust\x18\x03 \x01(\x05\"6\n\x11ToolRegistryEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bis_external\x18\x02 \x01(\x08\"i\n\x0cToolRegistry\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x10\n\x08revision\x18\x02 \x01(\t\x12\x36\n\x05tools\x18\x03 \x03(\x0b\x32\'.tessera_proto.xds.v1.ToolRegistryEntry\"\xae\x01\n\x0bTrustConfig\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x10\n\x08revision\x18\x02 \x01(\t\x12H\n\x0ctrust_levels\x18\x03 \x03(\x0b\x32\x32.tessera_proto.xds.v1.TrustConfig.TrustLevelsEntry\x1a\x32\n\x10TrustLevelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tessera.xds.v1.resources_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRUSTCONFIG_TRUSTLEVELSENTRY']._loaded_options = None
  _globals['_TRUSTCONFIG_TRUSTLEVELSENTRY']._serialized_options = b'8\001'
  _globals['_POLICYBUNDLE']._serialized_start=57
  _globals['_POLICYBUNDLE']._serialized_end=226
  _globals['_TOOLREQUIREMENT']._serialized_start=228
  _globals['_TOOLREQUIREMENT']._serialized_end=306
  _globals['_TOOLREGISTRYENTRY']._serialized_start=308
  _globals['_TOOLREGISTRYENTRY']._serialized_end=362
  _globals['_TOOLREGISTRY']._serialized_start=364
  _globals['_TOOLREGISTRY']._serialized_end=469
  _globals['_TRUSTCONFIG']._serialized_start=472
  _globals['_TRUSTCONFIG']._serialized_end=646
  _globals['_TRUSTCONFIG_TRUSTLEVELSENTRY']._serialized_start=596
  _globals['_TRUSTCONFIG_TRUSTLEVELSENTRY']._serialized_end=646
# @@protoc_insertion_point(module_scope)
