# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tessera/hooks/v1/hooks.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tessera/hooks/v1/hooks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctessera/hooks/v1/hooks.proto\x12\x16tessera_proto.hooks.v1\"\x93\x01\n\x19PostPolicyEvaluateRequest\x12\x0c\n\x04tool\x18\x01 \x01(\t\x12\x11\n\tprincipal\x18\x02 \x01(\t\x12\x15\n\rdecision_kind\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\x16\n\x0erequired_trust\x18\x05 \x01(\x05\x12\x16\n\x0eobserved_trust\x18\x06 \x01(\x05\"C\n\x1aPostPolicyEvaluateResponse\x12\x15\n\rdecision_kind\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"R\n\x17PostToolCallGateRequest\x12\x0c\n\x04tool\x18\x01 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x02 \x01(\t\x12\x11\n\tprincipal\x18\x03 \x01(\t\"9\n\x18PostToolCallGateResponse\x12\r\n\x05\x61llow\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"n\n\x1bPostDelegationVerifyRequest\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65legate\x18\x02 \x01(\t\x12\x10\n\x08\x61udience\x18\x03 \x01(\t\x12\x1a\n\x12\x61uthorized_actions\x18\x04 \x03(\t\"=\n\x1cPostDelegationVerifyResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tessera.hooks.v1.hooks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTPOLICYEVALUATEREQUEST']._serialized_start=57
  _globals['_POSTPOLICYEVALUATEREQUEST']._serialized_end=204
  _globals['_POSTPOLICYEVALUATERESPONSE']._serialized_start=206
  _globals['_POSTPOLICYEVALUATERESPONSE']._serialized_end=273
  _globals['_POSTTOOLCALLGATEREQUEST']._serialized_start=275
  _globals['_POSTTOOLCALLGATEREQUEST']._serialized_end=357
  _globals['_POSTTOOLCALLGATERESPONSE']._serialized_start=359
  _globals['_POSTTOOLCALLGATERESPONSE']._serialized_end=416
  _globals['_POSTDELEGATIONVERIFYREQUEST']._serialized_start=418
  _globals['_POSTDELEGATIONVERIFYREQUEST']._serialized_end=528
  _globals['_POSTDELEGATIONVERIFYRESPONSE']._serialized_start=530
  _globals['_POSTDELEGATIONVERIFYRESPONSE']._serialized_end=591
# @@protoc_insertion_point(module_scope)
