apiVersion: v1
kind: Namespace
metadata:
  name: tessera-mesh
  labels:
    app.kubernetes.io/name: tessera-mesh
    app.kubernetes.io/managed-by: kubectl
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
  annotations:
    tessera.dev/version: "0.13.0"
