apiVersion: v1
kind: Service
metadata:
  name: tessera-mesh
  namespace: tessera-mesh
  labels:
    app.kubernetes.io/name: tessera-mesh
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: kubectl
  annotations:
    tessera.dev/version: "0.13.0"
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    app.kubernetes.io/name: tessera-mesh
