apiVersion: v1
kind: ServiceAccount
metadata:
  name: tessera-mesh
  namespace: tessera-mesh
  labels:
    app.kubernetes.io/name: tessera-mesh
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: kubectl
  annotations:
    tessera.dev/version: "0.13.0"
automountServiceAccountToken: false
